### PR TITLE
feat: Fix V1 For Bugs and Maintainance of Site

### PR DESCRIPTION
**Pull request by DWE-CLOUD**
- [x] Fix the Data Science Logo
- [x] Correct the Header Buttons
- [x] Connect the Buttons with the Sections
- [x] Fix the text touching the sides of box . Also of the Icon

### CODE REVIEW

**Comment by DWE-CLOUD** [comment]
Fix V1 includes little fixes and addition to the main page like Logo is fixed , the icon sizing is fixed in the lightbox , the text is fixed which was touching the sides and a smooth scroll animation

**Comment by DWE-CLOUD** [comment]
- [ ] Remove the excess area
- [ ] Fix the resolution and scaling

**Comment by DWE-CLOUD** [comment]
Fix of the Resolution and scaling is under testing on different display .. Will update shortly

**Comment by DWE-CLOUD** [comment]
Fixed the Scroll which was causing the Issue in some displays

**Review by yogita005 — APPROVED** [review]
GREAT WORKKK

**Comment by LordHarsh** [comment]
LGTM!!🚀

**Pull request merged**
